# ==================================================
# APPLICATION
# ==================================================
spring.application.name=aarambh-lead-management
server.port=8080

# ==================================================
# MYSQL DATABASE
# ==================================================
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/aarambh_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata}

spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==================================================
# JPA / HIBERNATE
# ==================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==================================================
# EMAIL
# ==================================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==================================================
# APP EMAIL
# ==================================================
app.mail.admin-to=${APP_MAIL_ADMIN_TO:aarambhluminouslearning@gmail.com}
app.mail.company-name=Aarambh Luminous Learning

# ==================================================
# RAZORPAY
# ==================================================
razorpay.key.id=${RAZORPAY_KEY_ID:}
razorpay.key.secret=${RAZORPAY_KEY_SECRET:}
razorpay.currency=INR
razorpay.company.name=Aarambh Luminous Learning

# ==================================================
# JACKSON
# ==================================================
spring.jackson.time-zone=Asia/Kolkata
